### ISSUE TITLE
Remove basic-card logic

### ISSUE THREAD

**Issue by maxlgu** [GoogleChromeLabs/paymentrequest-show#2]
Now that basic-card content has been deprecated from w3c web payment spec[1], we should take down or migrate the basic-card dependencies in this demo.

[1] https://www.w3.org/TR/payment-method-basic-card/

**Comment by maxlgu** [comment]
The migration of basic-card logic in this example will take some effort, because basic-card is the only method used to demo show(). Without using basic-card, we will use a web-based payment handler instead, which will involve adding the payment handler installation logic.

**Comment by sibelius** [comment]
any plans to fix this ?

**Comment by rsolomakhin** [comment]
https://paymentrequest.show/demo does not have `basic-card`. Which demo is this referring to?

**Comment by sibelius** [comment]
can we get payerName, payerEmail, payer data inside the /show ?

inside the https://bobbucks.dev/pay HTML ?

or just when returning a payment response ?

**Comment by rsolomakhin** [comment]
The flow of data is from the payment app or from the user agent (the browser) to the website. If the website sends you the payerName, payerEmail, and payer data, then the https://bobbucks.dev/pay HTML can get it. See some tutorials on https://web.dev/explore/payments and please ask this questions on payments-dev@chromium.org mailing list.

**Comment by rsolomakhin** [comment]
Closing this issue, as https://paymentrequest.show/demo appears to not have anything `basic-card` related.
